/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '7/26/19, 4:10 PM' 
 * Generated by 'Student' 
 * Generated on server 'GA03205-12.NA.SAS.COM' 
 * Generated on SAS platform 'X64_10PRO WIN' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' 
 * Generated on web client 'http://localhost:49901/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257BD2CC3CBE-D16D-443A-AC99-D8EB4CA5349A%257D' 
 *
 */

libname prod "D:\Github\ML_SAS\eproduce";

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=prod.eproduce out=Work.preProcessedData;
	by country year;
run;
/* Expontential Smoothing: LINEAR (HOLT)*/
proc esm data=Work.preProcessedData back=0 lead=5 plot=(corr errors 
		modelforecasts) 
		out=prod.eprod_lr_output 
		outest=prod.eprod_lr_est 
		outstat=prod.eprod_lr_fit 
		outfor=prod.eprod_lr_forecast 
		outsum=prod.eprod_lr_summary;
	by country;
	id year interval=day;
	forecast eproduct / alpha=0.05 model=linear transform=none;
run;

/*proc delete data=Work.preProcessedData;*/
/*run;*/

proc contents; run;

/**/
/*proc sgplot data=consume.econsume_dt_forecast; by country;*/
/*  band    X=Date upper=U95 lower=L95;*/
/*  series  X=Date Y=Forecast;*/
/*  scatter X=Date Y=Actual;*/
/*  refline "01jan2002"d /axis=X;*/
/*quit;*/
