/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '7/26/19, 4:10 PM' 
 * Generated by 'Student' 
 * Generated on server 'GA03205-12.NA.SAS.COM' 
 * Generated on SAS platform 'X64_10PRO WIN' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' 
 * Generated on web client 'http://localhost:49901/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257BD2CC3CBE-D16D-443A-AC99-D8EB4CA5349A%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=ML.ECONSUME out=Work.preProcessedData;
	by country date;
run;

proc esm data=Work.preProcessedData back=0 lead=5 plot=(corr errors 
		modelforecasts) outest=ml.econsume_dt_est outstat=ml.econsume_dt_fit 
		outfor=ml.econsume_dt_forecast outsum=ml.econsume_dt_summary;
	by country;
	id date interval=day;
	forecast econsume / alpha=0.05 model=damptrend transform=none;
run;

proc delete data=Work.preProcessedData;
run;